---
id: 483633
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: latest
polling_url: https://hsk-trmnl.kevinjungchang.workers.dev/word?hsk=1,2,3
polling_headers: ''
name: Traditional Chinese Flashcard
description: Classic HSK 1–3 flashcards
refresh_interval: 15
